/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import static Interfaz.Window.main;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import proyecto2.so.Main;
import static proyecto2.so.Main.admin;
import static proyecto2.so.Main.w;

/**
 *
 * @author jesusmachta
 */
public class VideoStart extends javax.swing.JFrame  implements ActionListener{
    public Timer timer;
    
    
    

    /**
     * Creates new form VidieoStart
     */
    public VideoStart() {
        initComponents();
        this.setLocationRelativeTo(null);
        
       timer=new Timer(13500, this);
       timer.start(); 
        
        
        timer.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
//                 Main.w = null;
                try {
                    
                  
//                    Main.w.setVisible(true);
//                    crearPersonajes();
                cerrar();
                } catch (InterruptedException ex) {
                    Logger.getLogger(VideoStart.class.getName()).log(Level.SEVERE, null, ex);
                }
                timer.stop();
//                 w.setVisible(true);
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        } );
        
        
        
        
        
//        timer.addActionListener((java.awt.event.ActionEvent evt) -> {
//            try {
//                cerrar();
//            } catch (InterruptedException ex) {
//                Logger.getLogger(VideoStart.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        });
        
        
        
    }
    
    public void crearPersonajes() throws InterruptedException{
             admin.crearPersonajes();
            Main.w.colaStarTrek1.setText(admin.printCola(admin.getCola1StarTrek()));
            Main.w.colaStarTrek2.setText(admin.printCola(admin.getCola2StarTrek()));
            Main.w.colaStarTrek3.setText(admin.printCola(admin.getCola3StarTrek()));
            Main.w.colaStarTrekRefuerzo.setText(admin.printCola(admin.getColaRefuerzoStarTrek()));

            Main.w.colaStarWars1.setText(admin.printCola(admin.getCola1StarWars()));
            Main.w.colaStarWars2.setText(admin.printCola(admin.getCola2StarWars()));
            Main.w.colaStarWars3.setText(admin.printCola(admin.getCola3StarWars()));
            Main.w.colaStarWarsRefuerzo.setText(admin.printCola(admin.getColaRefuerzoStarWars()));
        }
    
    private void cerrar() throws InterruptedException{
        this.setVisible(false); 
//        timer.stop();
//        WindWiow w = new Window();
        System.out.println("Hola");
           
//        w.setVisible(true);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Purple And Black Neon Minimalist Game On Intro Video.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VideoStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VideoStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VideoStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VideoStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VideoStart().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
       
       
 {
//                Main.w = null;
                try {
                    
                  
                    Main.w.setVisible(true);
//                    crearPersonajes();
                cerrar();
                } catch (InterruptedException ex) {
                    Logger.getLogger(VideoStart.class.getName()).log(Level.SEVERE, null, ex);
                }
                timer.stop();
//                 w.setVisible(true);
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
    }

//    @Override
//    public void actionPerformed(ActionEvent e) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }

//    @Override
//    public void actionPerformed(ActionEvent e) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }
}
